In [12]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [1]:
import sys
import os

# Add the parent directory to the Python path
sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))

In [2]:
import pandas as pd

from src.config import TRANSFORMED_DATA_DIR

features_and_targets = pd.read_parquet(TRANSFORMED_DATA_DIR / "tabular_data.parquet")

In [3]:
features = features_and_targets.iloc[:, :-1]
targets = features_and_targets["target"]

In [6]:
features[features['pickup_location_id']=='HB101']

,rides_t-672,rides_t-671,rides_t-670,rides_t-669,rides_t-668,rides_t-667,rides_t-666,rides_t-665,rides_t-664,rides_t-663,...,rides_t-8,rides_t-7,rides_t-6,rides_t-5,rides_t-4,rides_t-3,rides_t-2,rides_t-1,pickup_hour,pickup_location_id
0,1,4,0,0,0,0,0,1,0,2,...,12,8,4,3,4,1,4,2,2023-01-29,HB101
1,1,1,0,0,0,0,0,0,3,3,...,5,3,5,4,3,0,0,1,2023-01-30,HB101
2,1,0,0,0,0,0,0,2,6,1,...,3,11,15,3,5,1,0,0,2023-01-31,HB101
3,0,0,0,0,0,0,0,2,4,0,...,6,15,12,5,1,1,0,0,2023-02-01,HB101
4,0,0,0,0,0,0,0,2,4,1,...,5,12,9,1,4,1,2,0,2023-02-02,HB101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
332,0,0,0,0,0,0,3,0,2,1,...,2,5,3,3,1,3,1,2,2023-12-27,HB101
333,0,0,0,0,0,0,0,3,3,2,...,7,3,1,2,1,2,0,1,2023-12-28,HB101
334,0,0,0,0,0,0,2,1,9,2,...,7,5,1,6,1,4,1,0,2023-12-29,HB101
335,3,3,0,0,0,0,0,0,2,1,...,5,3,3,1,9,1,3,3,2023-12-30,HB101
336,8,2,2,0,0,0,0,0,0,0,...,0,3,5,3,0,2,0,1,2023-12-31,HB101

In [9]:
from src.plot_utils import plot_aggregated_time_series

plot_aggregated_time_series(features, targets, pickup_location_id='HB101')

TypeError: plot_aggregated_time_series() got an unexpected keyword argument 'pickup_location_id'